PLAYER_SPEED = 5
CHAR_POSITION = 100
MIN_TURNING_SPACING = 150 -- 꼭지점 사이의 x 거리
MAX_TURNING_SPACING = 500
MIN_BUILDING_Y = 30 -- -- 빌딩 높이 
MAX_BUILDING_Y = 170
MIN_PASS_SPACING = 100 ---- 통과 간격
MAX_PASS_SPACING = 200
ONCE_CREATING_SIZE = 480 ---- 중간 장애물 거리
MIN_MIDDLE_DISTANCE = 300
MAX_MIDDLE_DISTANCE = 500
MIN_PASS_MARGIN = 60
MIN_TURNING_SPACING = 5


ZERO_DEC_VALUE = -0.09
INC_VALUE_IN_ZERO = 12
INC_VALUE_IN_NORMAL = 13
CRASH_DEC_VALUE_IN_NORMAL = 0
CRASH_DEC_VALUE_IN_ZERO = -40
SCORE_PER_BUILDING = 100 -- 건물 하나 지날 때...
COIN_HEIGHT = 40 -- 동전 높이.
function score(currentCombo)
	return currentCombo * 500
end

function updateBalance(currentCombo, bZero, timeAfterZero)
	
end



